modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/pog5/mc-leashplayers/issues"

[[mods]]
modId = "leashmod"
version = "${version}"
displayName = "Leashable Players"
authors = "pog5, terminalmaid"
description = '''
A mod that lets you leash players with configurable gamerules!
'''
logoFile = "assets/leashmod/icon.png"

[[mixins]]
config = "leashmod.mixins.json"

[[dependencies.leashmod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leashmod]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "BOTH"
